FROM python:3.9.1-alpine
# Update & Install dependencies
RUN apk update
RUN apk add --no-cache --update \
    openssl \
    ca-certificates \
    bzip2-dev \
    zlib-dev \
    readline-dev \
    build-base \
    linux-headers
RUN apk add cmake
RUN python -m pip install --upgrade pip
RUN apk --update add gcc libgcc musl-dev jpeg-dev zlib-dev
COPY ./requirements.txt requirements.txt
RUN python -m pip install -r requirements.txt
#Do not update anything above
WORKDIR app
COPY __init__.py module/__init__.py
COPY scheme module/scheme
COPY access module/access
COPY configs module/configs
COPY content module/content
COPY test module/test
ENTRYPOINT [ "python", "-m", "unittest"]